feat" Added jit network policies
cloudquery/cq-provider-azure pull request #124
Opened 2022-02-01 09:10 UTC by amanenk

- added jit network policies for HIPAA implementation

2022-02-01 09:55 UTC, michelvocks approved these changes
LGTM. Minor nit

2022-02-01 09:55 UTC, michelvocks commented on resources/services/security/jit_network_access_policies.go
> +	//
If it is not necessary we should delete it.

2022-02-06 16:08 UTC, roneli requested changes
nit: change migrations to v0.5.0 version

2022-02-07 10:55 UTC, spangenberg approved these changes
LGTM, just migration file name needs change

2022-02-09 13:30 UTC, roneli requested changes

2022-02-09 13:30 UTC, roneli commented on resources/services/security/jit_network_access_policies.go
> +						Type:        schema.TypeString,
type inet?

2022-02-09 13:30 UTC, roneli commented on resources/services/security/jit_network_access_policies.go
> +						Name:        "azure_security_jit_network_access_policy_virtual_machine_ports",
would maybe make this a json if its not critical for the queries

2022-02-10 11:40 UTC, roneli approved these changes

2022-02-10 11:41 UTC, merged