feat: Added sql managed instances
cloudquery/cq-provider-azure pull request #131
Opened 2022-02-04 14:47 UTC by amanenk

Added sql managed instances and its relations required to fulfill HIPAA queries

2022-02-06 16:24 UTC, roneli requested changes
LGTM, requires fix to the migrations (v0.5.0) + e2e testing, they should work now on PR once you rebase from main.

2022-02-07 10:41 UTC, spangenberg approved these changes
LGTM, apart from the migration file name

2022-02-10 13:55 UTC, irmatov requested changes
Remove unnecessary Multiplex and DeleteFilter, otherwise LGTM (there are a few other nits around descriptions).

2022-02-10 13:55 UTC, irmatov commented on resources/services/sql/managed_databases.go
> +		DeleteFilter: client.DeleteSubscriptionFilter,
As this is a relation on instances there is no need for Multiplex nor DeleteFilter.

2022-02-10 13:55 UTC, irmatov commented on resources/services/sql/managed_databases.go
> +				Description: "Conditional",
nit: incomplete description?

2022-02-10 13:55 UTC, irmatov commented on resources/services/sql/managed_instances.go
> +				Description: "The name of the SKU, typically, a letter + Number code, e.g",
nit: description can be cleaned up a bit (remove trailing `, e.g`)

2022-02-10 13:55 UTC, irmatov commented on resources/services/sql/managed_instances.go
> +				Description: "The tier or edition of the particular SKU, e.g",
nit: same as above

2022-02-10 13:55 UTC, irmatov commented on resources/services/sql/managed_instances.go
> +				Description: "Specifies the mode of database creation.  Default: Regular instance creation.  Restore: Creates an instance by restoring a set of backups to specific point in time",
nit: description can be shortened.

2022-02-13 13:48 UTC, roneli requested changes
LGTM, minor nits and we can merge.

2022-02-13 13:48 UTC, roneli commented on docs/tables/azure_sql_managed_instance_private_endpoint_connections.md
> +|private_link_service_connection_state_actions_required|text|The private link service connection description.|
connection_status, connection_description, connection_actions_required

2022-02-13 13:48 UTC, roneli commented on resources/services/sql/managed_databases.go
> +func SqlManagedDatabases() *schema.Table {
nit: would make this unexported.

2022-02-16 07:51 UTC, roneli requested changes
LGTM, to more minor nits.

2022-02-16 07:51 UTC, roneli commented on docs/tables/azure_sql_managed_instances.md
> +|administrator_login_password|text|The administrator login password (required for managed instance creation)|
would maybe not fetch this field `administrator_login_password` , although I am pretty sure it doesn't get fetched in read.

2022-02-16 07:51 UTC, roneli commented on resources/services/sql/managed_instances.go
> +					},
didn't we say in previous review to shorten these?

2022-02-16 22:09 UTC, roneli approved these changes

2022-02-16 22:09 UTC, merged