feat: Added sql database vulnerability scans
cloudquery/cq-provider-azure pull request #138
Opened 2022-02-08 14:28 UTC by amanenk

2022-02-08 16:12 UTC, roneli commented on resources/provider/migrations/timescale/5_v0.5.0.up.sql
> +CREATE TABLE IF NOT EXISTS "azure_sql_database_db_vulnerability_assessment_scans"
these migrations should be in next version v0.6.0

2022-02-08 16:13 UTC, roneli commented on resources/services/sql/databases.go
> +				Description: "The tier or edition of the particular SKU, e.g",
nit: revert descriptions

2022-02-13 14:01 UTC, roneli requested changes
A little hard to review with lots of shifting, looks good in general, noticed some descriptions going missing + ignore in tests missing (we should add ability to mark them when generating)

2022-02-17 12:35 UTC, roneli approved these changes
LGTM

2022-02-17 13:08 UTC, merged

2022-03-10 15:22 UTC, disq commented on resources/services/sql/databases.go
> -				Options:     schema.TableCreationOptions{PrimaryKeys: []string{"database_cq_id", "id"}},
Where did the PK go?

2022-03-10 15:22 UTC, disq commented on resources/services/sql/databases.go
> -				Options:     schema.TableCreationOptions{PrimaryKeys: []string{"database_cq_id", "id"}},
Missing PK

2022-03-10 15:22 UTC, disq commented on resources/services/sql/databases.go
> +				Description: "DatabaseBlobAuditingPolicy a database blob auditing policy",
Bad description?