feat: Implement Managed HSM resource
cloudquery/cq-provider-azure pull request #140
Opened 2022-02-09 11:37 UTC by irmatov

2022-02-09 14:14 UTC, roneli requested changes
missing PK

2022-02-09 14:14 UTC, roneli commented on resources/services/keyvault/keyvault_managed_hsm.go
> +		Name:         "azure_keyvault_managed_hsm",
missing PK

2022-02-10 07:41 UTC, amanenk requested changes
LGTM. one nit

2022-02-10 07:41 UTC, amanenk commented on resources/services/keyvault/keyvault_managed_hsm.go
> +		DeleteFilter: client.DeleteSubscriptionFilter,
Options.PrimaryKeys missing

2022-02-10 08:28 UTC, irmatov commented on resources/services/keyvault/keyvault_managed_hsm.go
> +		Name:         "azure_keyvault_managed_hsm",
Fixed, thanks

2022-02-10 08:28 UTC, irmatov commented on resources/services/keyvault/keyvault_managed_hsm.go
> +		DeleteFilter: client.DeleteSubscriptionFilter,
Fixed, thanks

2022-02-10 08:48 UTC, amanenk approved these changes

2022-02-13 13:53 UTC, roneli approved these changes

2022-02-13 13:53 UTC, merged