feat: Added search services
cloudquery/cq-provider-azure pull request #149
Opened 2022-02-17 09:02 UTC by zagronitay

2022-02-17 13:26 UTC, irmatov approved these changes
LGTM

2022-02-18 09:58 UTC, amanenk requested changes

2022-02-18 09:58 UTC, amanenk commented on resources/services/search/services.go
> +				Description: "A list of IP restriction rules that defines the inbound network(s) with allowing access to the search service endpoint",
can `inetarray` be used there?

2022-02-18 09:58 UTC, amanenk commented on resources/services/search/services.go
> +						Name:        "private_link_service_connection_state_status",
a few lines can be shortened
```
  column "private_link_service_connection_state_status" {
    rename = "connection_status"
  }
  column "private_link_service_connection_state_description" {
    rename = "connection_description"
  }
  column "private_link_service_connection_state_actions_required" {
    rename = "connection_actions_required"
  }
```

2022-03-07 07:35 UTC, roneli reviewed
nothing more to add other than andrii's comments

2022-03-07 17:16 UTC, roneli approved these changes
LGTM

2022-03-09 10:05 UTC, amanenk approved these changes

2022-03-09 10:06 UTC, merged