feat: Implement StreamAnalytics Jobs
cloudquery/cq-provider-azure pull request #159
Opened 2022-02-22 13:01 UTC by irmatov

2022-02-23 08:20 UTC, amanenk requested changes
Looks good. A few minor changes

2022-02-23 08:20 UTC, amanenk commented on resources/services/streamanalytics/jobs_test.go
> +package streamanalytics
rename file to jobs_mock_test

2022-02-23 08:20 UTC, amanenk commented on resources/services/streamanalytics/jobs.go
> +		DeleteFilter: client.DeleteSubscriptionFilter,
add primary keys

2022-02-23 08:20 UTC, amanenk commented on resources/services/streamanalytics/jobs.go
> +				Name:        "events_late_arrival_max_delay_in_seconds",
maybe remove in_seconds

2022-02-23 08:40 UTC, irmatov commented on resources/services/streamanalytics/jobs_test.go
> +package streamanalytics
Done, thanks

2022-02-23 08:41 UTC, irmatov commented on resources/services/streamanalytics/jobs.go
> +		DeleteFilter: client.DeleteSubscriptionFilter,
Added, thanks.

2022-02-23 08:42 UTC, irmatov commented on resources/services/streamanalytics/jobs.go
> +				Name:        "events_late_arrival_max_delay_in_seconds",
Good point, removed!

2022-03-04 11:25 UTC, disq approved these changes
LGTM

2022-03-04 16:47 UTC, spangenberg approved these changes

2022-03-07 13:11 UTC, amanenk approved these changes

2022-03-07 13:26 UTC, merged