Network watchers
cloudquery/cq-provider-azure pull request #21
Opened 2021-06-29 11:28 UTC by fdistorted

2021-07-01 13:26 UTC, irmatov requested changes

2021-07-01 14:19 UTC, fdistorted commented on resources/network_watchers.go
> +		svc := meta.(*client.Client).Services().Network.Watchers
it is also a duplicate of one that is already out of the loop.

2021-07-01 14:19 UTC, fdistorted commented on resources/network_watchers.go
> +		svc := meta.(*client.Client).Services().Network.Watchers
I am a bad copypaster ^^

2021-07-02 11:05 UTC, irmatov approved these changes
LGTM

2021-07-08 08:35 UTC, roneli approved these changes
LGTM, fix conflicts and we can merge

2021-07-09 16:46 UTC, merged