Add SQL blob auditing policies
cloudquery/cq-provider-azure pull request #30
Opened 2021-07-06 06:15 UTC by irmatov

2021-07-06 06:15 UTC, irmatov commented
WIP/ to be reviewed after previous PRs.

2021-07-13 13:25 UTC, fdistorted approved these changes
LGTM

2021-07-13 15:12 UTC, roneli requested changes
Minor comments, mostly to reduce long descriptions

2021-07-13 15:12 UTC, roneli commented on resources/sql_databases.go
> +						Description: "Specifies the Actions-Groups and Actions to audit  The recommended set of action groups to use is the following combination - this will audit all the queries and stored procedures
shorten this description

2021-07-13 15:12 UTC, roneli commented on resources/sql_servers.go
> +						Description: "Specifies whether audit events are sent to Azure Monitor In order to send the events to Azure Monitor, specify 'state' as 'Enabled' and 'isAzureMonitorTargetEnabled' as true  When
shorten description

2021-07-13 15:12 UTC, roneli commented on resources/sql_servers.go
> +						Description: "Specifies the Actions-Groups and Actions to audit  The recommended set of action groups to use is the following combination - this will audit all the queries and stored procedures
shorten description

2021-07-13 15:12 UTC, roneli commented on resources/sql_servers.go
> +						Description: "Specifies the identifier key of the auditing storage account If state is Enabled and storageEndpoint is specified, not specifying the storageAccountAccessKey will use SQL server s
shorten description

2021-07-13 15:12 UTC, roneli commented on resources/sql_databases.go
> +						Description: "Specifies whether audit events are sent to Azure Monitor In order to send the events to Azure Monitor, specify 'state' as 'Enabled' and 'isAzureMonitorTargetEnabled' as true  When
shorten description

2021-07-13 15:12 UTC, roneli commented on resources/sql_databases.go
> +						Description: "Specifies the state of the policy If state is Enabled, storageEndpoint or isAzureMonitorTargetEnabled are required Possible values include: 'BlobAuditingPolicyStateEnabled', 'Blob
shorten description

2021-07-13 15:12 UTC, roneli commented on resources/sql_databases.go
> +						Description: "Specifies the blob storage endpoint (eg https://MyAccountblobcorewindowsnet) If state is Enabled, storageEndpoint or isAzureMonitorTargetEnabled is required",
shorten description

2021-07-14 06:49 UTC, irmatov commented on resources/sql_databases.go
> +						Description: "Specifies the blob storage endpoint (eg https://MyAccountblobcorewindowsnet) If state is Enabled, storageEndpoint or isAzureMonitorTargetEnabled is required",
Done

2021-07-14 06:49 UTC, irmatov commented on resources/sql_databases.go
> +						Description: "Specifies the Actions-Groups and Actions to audit  The recommended set of action groups to use is the following combination - this will audit all the queries and stored procedures
Done

2021-07-14 06:50 UTC, irmatov commented on resources/sql_databases.go
> +						Description: "Specifies the state of the policy If state is Enabled, storageEndpoint or isAzureMonitorTargetEnabled are required Possible values include: 'BlobAuditingPolicyStateEnabled', 'Blob
Done

2021-07-14 06:50 UTC, irmatov commented on resources/sql_databases.go
> +						Description: "Specifies whether audit events are sent to Azure Monitor In order to send the events to Azure Monitor, specify 'state' as 'Enabled' and 'isAzureMonitorTargetEnabled' as true  When
Done

2021-07-14 06:51 UTC, irmatov commented on resources/sql_servers.go
> +						Description: "Specifies the identifier key of the auditing storage account If state is Enabled and storageEndpoint is specified, not specifying the storageAccountAccessKey will use SQL server s
Done

2021-07-14 06:52 UTC, irmatov commented on resources/sql_servers.go
> +						Description: "Specifies the Actions-Groups and Actions to audit  The recommended set of action groups to use is the following combination - this will audit all the queries and stored procedures
Done

2021-07-14 06:52 UTC, irmatov commented on resources/sql_servers.go
> +						Description: "Specifies whether audit events are sent to Azure Monitor In order to send the events to Azure Monitor, specify 'state' as 'Enabled' and 'isAzureMonitorTargetEnabled' as true  When
Done

2021-07-18 14:48 UTC, roneli reviewed
New SDK supports INET/Mac/IP types we should change to the correct types if possible.

2021-07-19 07:26 UTC, irmatov commented
@roneli I don't think this PR adds any fields of these types in new resources

2021-07-19 09:30 UTC, roneli approved these changes

2021-07-19 09:32 UTC, merged